### ISSUE TITLE
build failed with Hunk #1 FAILED at 54

### ISSUE THREAD

**Issue by robertaramar** [david0/homebrew-audio#28]
Hi,

I get this when I run the build command:

`==> Installing calf from david0/audio
==> Patching
==> Applying d2f174083d97ce0f6930fc28764fdec80810f464.patch
patching file configure.ac
Hunk #1 succeeded at 159 with fuzz 2 (offset 21 lines).
patching file src/Makefile.am
Hunk #1 FAILED at 54.
1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.am.rej

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/david0/homebrew-audio/issues
`
Anything I can do about that?
Regards,
Robert

**Comment by ChycoFWD** [comment]
Hi, the same thing happens here.
-----

Last login: Wed Jun 15 18:31:56 on ttys000
chicofwd@Thiagos-MacBook-Pro ~ % brew install --HEAD calf   
==> Downloading https://github.com/david0/calf/commit/d2f174083d97ce0f6930fc2876
Already downloaded: /Users/chicofwd/Library/Caches/Homebrew/downloads/e9540cf450abed6e2754989c4a940afae7435728c4ff5e186c23cb15bbbeb9ba--d2f174083d97ce0f6930fc28764fdec80810f464.patch
==> Cloning https://github.com/calf-studio-gear/calf.git
Updating /Users/chicofwd/Library/Caches/Homebrew/calf--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 024e9dea Merge pull request #304 from jwatt/patch-1
==> Installing calf from david0/audio
==> Patching
==> Applying d2f174083d97ce0f6930fc28764fdec80810f464.patch
patching file configure.ac
Hunk #1 succeeded at 159 with fuzz 2 (offset 21 lines).
patching file src/Makefile.am
Hunk #1 FAILED at 54.
1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.am.rej

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/david0/homebrew-audio/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
chicofwd@Thiagos-MacBook-Pro ~ %  

-----
greetings from Brazil

**Comment by david0** [comment]
Thanks for the report. The makefile was updated upstream breaking the patch.
I updated my PR calf-studio-gear/calf#46 (unmerged since 7 years...)  and added the new patch to the formula.
Please give it a try.
